# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [3]:
import numpy as np
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2
print ("Lösning_konskapkontroll_1_1_Numpy")

# Skriv ut matriserna ochlösning
print("Matris B:")
print(B)
print("\nMatris C:")
print(C)
print("\nElementvis subtraktion (B - C):")
print(B - C)
print("\nElementvis multiplikation (B * C):")
print(B * C)
print("\nMatris-multiplikation (B @ C):")
print(B @ C)

Lösning_konskapkontroll_1_1_Numpy
Matris B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matris C:
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementvis subtraktion (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementvis multiplikation (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matris-multiplikation (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [4]:
import numpy as np
B = np.arange(1, 10).reshape(3, 3)
print("skafades 3*3 matrix som B")
print(B)
print("/nElementvis exponentiering")
exp_matrix = np.exp(B)
print("exp_matrix")
print("/nminsta värdet i hela matrisen")
min_value = np.min(B)
print(min_value)
print("/nminsta värdet i varje rad")
min_row = np.min(B, axis=1)
print(min_row)
print("minsta värdet i varje kolumn") 
min_column = np.min(B, axis=0)
print(min_column)
print("/nminsta värdet i hela matrisen") 
min_index = np.argmin(B)
print("/nIndex för minsta värdet i varje rad")
min_index_row = np.argmin(B, axis=1)
print(min_index_row)
print("/nSummera alla element")
sum_all_elements = np.sum(B)
print(sum_all_elements)
print("/nMedelvärde för varje kolumn")
sum_all_elements = np.mean(B, axis=0)
print(sum_all_elements)
print("/nMedian för varje kolumn") 
median_column = np.median(B, axis=0)
print(median_column)


skafades 3*3 matrix som B
[[1 2 3]
 [4 5 6]
 [7 8 9]]
/nElementvis exponentiering
exp_matrix
/nminsta värdet i hela matrisen
1
/nminsta värdet i varje rad
[1 4 7]
minsta värdet i varje kolumn
[1 2 3]
/nminsta värdet i hela matrisen
/nIndex för minsta värdet i varje rad
[0 0 0]
/nSummera alla element
45
/nMedelvärde för varje kolumn
[4. 5. 6.]
/nMedian för varje kolumn
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [5]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [7]:
""" detta som att man vill ha andra raden (index 1), och returnerar alla kolumner för den raden."""

' detta som att man vill ha andra raden (index 1), och returnerar alla kolumner för den raden.'

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [8]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [10]:
"""np.nditer(A) skapar en iterator som itererar elementvis över varje värde i matrisen"""
A= ([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

for i in np.nditer(A):
    print(i)

(array(1), array(6), array(11))
(array(2), array(7), array(12))
(array(3), array(8), array(13))
(array(4), array(9), array(14))
(array(5), array(10), array(15))


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [11]:
"""En array med tre axlar betyder att arrayen är tredimensionell:

Den första axeln har storleken 2 , det finns två "block" i arrayen.
Den andra axeln har storleken 3 , varje block har tre rader.
Den tredje axeln har storleken -1 ,att Python ska räkna ut vad den tredje dimensionen ska vara"""
"""paython reknar Python räkna ut att den tredje dimensionen måste vara 5 för att det totala antalet element (30) ska kunna fördelas jämt"""
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print("-"*100)
print("b ska vara :")
print(b)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
----------------------------------------------------------------------------------------------------
b ska vara :
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [12]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [13]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [14]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [15]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that the inputs are numpy ndarrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray.")
    
    # Validate the operation argument
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'.")
    
    # Perform addition
    if operation == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must be the same size for addition.")
        return matrix1 + matrix2
    
    # Perform multiplication
    elif operation == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix.")
        return np.dot(matrix1, matrix2)

# Example usage:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

# Adding the matrices
result_add = add_mult_matrices(matrix_a, matrix_b, 'add')
print("Addition result:\n", result_add)

# Multiplying the matrices
result_multiply = add_mult_matrices(matrix_a, matrix_b, 'multiply')
print("Multiplication result:\n", result_multiply)


Addition result:
 [[ 6  8]
 [10 12]]
Multiplication result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [16]:
"""Uppgift 10.1.1. Definiera vektorn x enligt nedan.
x = (4, 3)
(a) Vilken dimension har vektorn x^2?
(b) Ber¨akna 5x.
(c) Ber¨akna 3x.
(d) Ber¨akna 5x + 3x.
(e) Ber¨akna 8x.
(f) Ber¨akna 4x − x.
(g) Ber¨akna x
⊤, vilken blir den nya dimensionen efter att
transponeringen utf¨orts?
(h) Ar ¨ x + x
⊤ definierat?
(i) Ber¨akna ∥x∥."""

#Definera v:
x = np.array([4, 3])
#(a) Vilken dimension har vektorn x^2
print("dimension har vektorn x^2:  ",np.ndim(x^2)) 
print("x^2 ska vara :", x^2)
print("--$$--"*2)
print("5x ska vara :", 5*x)
print("--$$--"*2)
print("3x ska vara :", 3*x)
print("--$$--"*2)
print("5x+3x ska vara :", (5*x)+(3*x))
print("--$$--"*2)
print("8x ska vara :", 8*x)
print("--$$--"*2)
print("4x-x ska vara :", (4 * x) - x)
print("--$$--"*2)
print("x_Transposw :", x.reshape(-1, 1))
print("--$$--"*2)
print("Norm x :", np.linalg.norm(x))
print("--$$--"*2)


dimension har vektorn x^2:   1
x^2 ska vara : [6 1]
--$$----$$--
5x ska vara : [20 15]
--$$----$$--
3x ska vara : [12  9]
--$$----$$--
5x+3x ska vara : [32 24]
--$$----$$--
8x ska vara : [32 24]
--$$----$$--
4x-x ska vara : [12  9]
--$$----$$--
x_Transposw : [[4]
 [3]]
--$$----$$--
Norm x : 5.0
--$$----$$--


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [24]:
#Skriv det linj¨ara ekvationssystemet nedan p˚a
#formen Ax = b.
"""3x1 + 2x2 + 4x3 = 7
2x1 + 3x2 + 8x3 = 4
4x1 + x2 + 3x3 = 11
7x1 + x2 + 5x3 = 9"""
#Verifiera att din l¨osning ¨ar korrekt genom att skriva ut matrismultiplikationen
#  Ax = b och dubbelkolla att du f˚ar tillbaka det ursprungliga ekvationssystemet.
print("--$$--"*2)
"""A = [[3, 2, 4],
     [2, 3, 8],
     [4, 1, 3],
     [7, 1, 5]]

x = [1, 1, 1]


b = [7, 4, 11, 9]"""
print("--$$--"*2)
import numpy as np

# Definiera matriserna och vektorn
A = np.array([[3, 2, 4],
              [2, 3, 8],
              [4, 1, 3],
              [7, 1, 5]])

b = np.array([7, 4, 11, 9])
X = np.linalg.lstsq(A, b) 
print("X som lösning är:", X)

--$$----$$--
--$$----$$--
X som lösning är: (array([ 2.13691417,  4.83412322, -1.89152185]), array([15.04002106]), np.int32(3), array([13.61546816,  4.59720879,  0.69620265]))


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [68]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)


[0 1 2 3]
[2 3]


In [79]:
#när vi användar index av elementer för att definera v2,detta är inte  nya variabel
#  uttan detta är/n ett referanc  eller en viwe till v1 index medan copy skappar ny
#  variabel med nya index.
# till mer förståelse :
import numpy as np

v1 = np.arange(4)
v2 = v1[-2:]

print("innan ändering:")
print("v1:", v1)
print("v2:", v2)

# om vi ändra sista elementet i v2 till 123 :
v2[-1] = 123

print("efter ändring:") 
print("v1:", v1)
print("v2:", v2)
print(v1.base)
print(v2.base)

innan ändering:
v1: [0 1 2 3]
v2: [2 3]
efter ändring:
v1: [  0   1   2 123]
v2: [  2 123]
None
[  0   1   2 123]
